name: github-actions.yml # ワークフローの名前を定義

on:
  push: # GitHubにpushされた時にワークフローを起動する

jobs:
  rspec:
    runs-on: ubuntu-latest # 実行環境
    defaults:
      run:
        working-directory: . # 作業ディレクトリを指定
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }} # GitHub Secretsを参照

    steps:
      - name: Checkout code # GitHubのリポジトリからコードをチェックアウトします。
        uses: actions/checkout@v2

      - name: Set up Ruby # Rubyのセットアップを行います。
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.3 # 使用するRubyのバージョンを指定します。
          bundler-cache: true # Bundlerのキャッシュを有効にします。

      - name: Cache node modules # Nodeモジュールをキャッシュします。
        uses: actions/cache@v3
        with:
          path: node_modules # キャッシュするディレクトリを指定します。
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }} # キャッシュのキーを指定します。
          restore-keys: |
            ${{ runner.os }}-node-  # 部分一致する最新のキャッシュを探します。

      - name: Bundler and gem install # Bundlerとgemのインストールを行います。
        run: |
          gem install bundler
          bundle install

      - name: Database create and migrate # データベースの作成とマイグレーションを実行します。
        run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test

      - name: Run rspec # RSpecを実行します。
        run: bundle exec rspec
